sudo: required
dist: trusty
language: c
python:
  - "3.6"
cache:
  apt: true
  directories:
  - /home/travis/postgresql
branches:
  except: [ /^open-.*$/ ]
env:
  global:
    # GitHub API token for citus-bot
    - secure: degV+qb2xHiea7E2dGk/WLvmYjq4ZsBn6ZPko+YhRcNm2GRXRaU3FqMBIecPtsEEFYaL5GwCQq/CgBf9aQxgDQ+t2CrmtGTtI9AGAbVBl//amNeJOoLe6QvrDpSQX5pUxwDLCng8cvoQK7ZxGlNCzDKiu4Ep4DUWgQVpauJkQ9nHjtSMZvUqCoI9h1lBy9Mxh7YFfHPW2PAXCqpV4VlNiIYF84UKdX3MXKLy9Yt0JBSNTWLZFp/fFw2qNwzFvN94rF3ZvFSD7Wp6CIhT6R5/6k6Zx8YQIrjWhgm6OVy1osUA8X7W79h2ISPqKqMNVJkjJ+N8S4xuQU0kfejnQ74Ie/uJiHCmbW5W2TjpL1aU3FQpPsGwR8h0rSeHhJAJzd8Ma+z8vvnnQHDyvetPBB0WgA/VMQCu8uEutyfYw2hDmB2+l2dDwkViaI7R95bReAGrpd5uNqklAXuR7yOeArz0ZZpHV0aZHGcNBxznMaZExSVZ5DVPW38UPn7Kgse8BnOWeLgnA1hJVp6CmBCtu+hKYt+atBPgRbM8IUINnKKZf/Sk6HeJIJZs662jD8/X93vFi0ZtyV2jEKJpouWw8j4vrGGsaDzTEUcyJgDqZj7tPJptM2L5B3BcFJmkGj2HO3N+LGDarJrVBBSiEjhTgx4NnLiKZnUbMx547mCRg2akk2w=
    # During push builds (not pull request builds), use custom-built PostgreSQL
    - USE_CUSTOM_PG=$([ -z $TRAVIS_PULL_REQUEST_SHA ] && echo "true")
matrix:
  fast_finish: true
  include:
    - env: PGVERSION=9.6
    - env: PGVERSION=10
    - env: PGVERSION=11
  allow_failures:	
    - env: PGVERSION=11
before_install:
  - git clone -b v0.7.9 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - setup_apt
  - curl https://install.citusdata.com/community/deb.sh | sudo bash
  - nuke_pg
  - pyenv versions
  - pyenv global 3.6
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - pip3 install --user pipenv
install:
  - install_uncrustify
  - install_pg
  - install_custom_pg
  - PIPENV_PIPFILE="${TRAVIS_BUILD_DIR}"/src/test/regress/Pipfile pipenv install --system --deploy
  - mitmproxy --version
  # download and install HLL and TopN manually, as custom builds won't satisfy deps
  # only install if performing non-11 build
  - |
    if [ "${PGVERSION}" != "11" ]; then
      apt-get download "postgresql-${PGVERSION}-hll=2.10.2.citus-1"
      sudo dpkg --force-confold --force-confdef --force-all -i *hll*.deb
    fi
  - |
    if [ "${PGVERSION}" != "11" ]; then
      apt-get download "postgresql-${PGVERSION}-topn=2.1.0"
      sudo dpkg --force-confold --force-confdef --force-all -i *topn*.deb
    fi
before_script: citus_indent --quiet --check
script: CFLAGS=-Werror pg_travis_multi_test check
after_success:
  - sync_to_enterprise
  - bash <(curl -s https://codecov.io/bash)
